### ISSUE TITLE
Graceful decompress

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/processor-decompress#14]
https://keboolaglobal.slack.com/archives/CCNV7TZUH/p1547023077013200

Umět pokračovata na nevalidních archivech. Může to bejt třeba nějakej optional parametr

```
{
    "definition": {
        "component": "keboola.processor-decompress"
    },
    "parameters": {
        "graceful": true
    }
}
```

a je `graceful` ten správnej termín? :-)

**Comment by odinuv** [comment]
graceful: having or showing grace or elegance. "she was a tall girl, slender and graceful"
grace: 1. smoothness and elegance of movement. 2. **courteous good will.**

ja myslim, ze je to dobrej termin :)
